image: Visual Studio 2022

environment:
  PLAYWRIGHT_BROWSERS_PATH: "%APPVEYOR_BUILD_FOLDER%\\pw-browsers"

install:
  - pip install playwright pyinstaller

build_script:
  # Chromium ni mahalliy papkaga o'rnatish
  - playwright install chromium

  # EXE yasash — brauzer ham ichiga qo'shiladi
  - pyinstaller --onefile --console --name "OdooBot" --add-data "pw-browsers;browsers" yuklash.py

artifacts:
  - path: dist\OdooBot.exe
    name: OdooBot-Windows-EXE