image: Visual Studio 2022

build_script:
  - pip install playwright pyinstaller
  - playwright install chromium
  - pyinstaller --onefile --console --name "OdooBot" yuklash.py

artifacts:
  - path: dist\OdooBot.exe
    name: OdooBot
